server:
  port: 7778
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/customers?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
    username: customers
    password: customers
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: '*'
info:
  app:
    name: "Customers"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}