server:
  port: 7778
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customers?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
info:
  app:
    name: "Customers"
    version: "0.0.1"