server:
  port: 7777
accounts:
  spring:
    jpa:
      database: mysql
      show-sql: true
      ddl-auto: update
    datasource:
      url: "jdbc:mysql://localhost:3306/accounts?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true"
      username: accounts
      password: accounts