accounts:
  server:
    port: 7777
  datasource:
    url: jdbc:mysql://localhost:3306/accounts?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
    username: accounts
    password: accounts
    ddl-auto: update
  allow-get-accounts: true
customers:
  server:
    port: 7778
  datasource:
    url: jdbc:mysql://localhost:3306/customers?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
    username: customers
    password: customers
    ddl-auto: update