server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accounts?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
info:
  app:
    name: "Accounts"
    version: "0.0.1"
application:
  allow-get-accounts: true