server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accounts?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
management:
  endpoints:
    web:
      exposure:
        include: '*'
info:
  app:
    name: "Accounts"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}
application:
  allow-get-accounts: true