server:
  port: 7777
accounts:
  datasource:
    driverClassName: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/accounts"
    username: accounts
    password: accounts
    ddl-auto: update