spring:
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka-client:
  fetchRegistry: true
  serviceUrl:
    defaultZone=http://localhost:8761/eureka/: