spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: banking
    password: banking
  jpa:
    hibernate:
      ddl-auto: update
eureka-client:
  fetchRegistry: true
  serviceUrl:
    defaultZone=http://localhost:8761/eureka/: