spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: banking
    password: banking
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: '*'
info:
  app:
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}
eureka-client:
  fetchRegistry: true
  serviceUrl:
    defaultZone=http://localhost:8761/eureka/: